### PR TITLE
Allow to compare between PlacedTile and Tile without converting

### LINKED ISSUE #122: Allow to compare between PlacedTile and Tile without converting

### PR DESCRIPTION
**Pull request by Lenetis**
Resolves #122

Also added a way to compare only features of two different PlacedTiles, without converting to Tile

### CODE REVIEW

**Review by Jackenmen — COMMENTED** [review]
I know this is a draft but I'd suggest calling this one `ExactEqualsTile` rather than `EqualsTile` to be consistent with how `Tile` does it. If needed (based on usage), an `Equals` equivalent should also be added.

**Comment by bstrzelecki** [comment]
[1.json](https://github.com/user-attachments/files/17188780/1.json)

**Comment by bstrzelecki** [comment]
OOM kill: 
[2.json](https://github.com/user-attachments/files/17188969/2.json)

**Comment by bstrzelecki** [comment]
Player 2 has 8 meeples on the board at the end of the game: 
[3.json](https://github.com/user-attachments/files/17189172/3.json)

**Comment by Lenetis** [comment]
@bstrzelecki all unit tests are passing. How can I reproduce these issues?

**Comment by bstrzelecki** [comment]
You can try using [python agent](https://github.com/YetAnotherSpieskowcy/Carcassonne-Neural-Network).

**Comment by Lenetis** [comment]
Tested on https://github.com/YetAnotherSpieskowcy/Carcassonne-Neural-Network, branches:
- main - sometimes fails tests, regardless of whether the changes from this PR are present or not
- async_agent - passes tests
- makefile_reorganizatio - passes tests
- greedy-agent - passes tests

I couldn't reproduce any issues with the details you provided

**Review by Jackenmen — APPROVED** [review]

**Pull request merged**
